apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000  # Target port of the Flask app inside the pod
  type: NodePort  # Exposes the service outside the cluster
